# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-01 04:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raccoonapp', '0002_raccoon_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('description', models.TextField(blank=True)),
                ('raccoon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raccoonapp.Raccoon')),
            ],
        ),
    ]
